#!/bin/bash
# Usage: scripts/build [command]
# Build an image for staging, production

# This makes sure the script fails on the first failing command
set -e

export GIT_TAG=`git describe --exact-match --tags $(git rev-parse HEAD)`

if [ -n "$GIT_TAG" ]; then
  . ./scripts/build-prod
fi
