#!/bin/bash

# This makes sure the script fails on the first failing command
set -e

. ./scripts/build-base

export TAG=`git describe --exact-match --tags $(git rev-parse HEAD)`

docker build --rm=false \
  --file=Dockerfile \
  --tag=$REPO_NAME:latest \
  --tag=$REPO_NAME:$TAG \
  .
docker push $REPO_NAME:latest
docker push $REPO_NAME:$TAG
